Vagrant.configure("2") do |config|
config.vm.box = "ubuntu12.04.3"
config.vm.box_url = "http://nitron-vagrant.s3-website-us-east-1.amazonaws.com/vagrant_ubuntu_12.04.3_amd64_virtualbox.box"
#config.vm.provision :shell, :path => "bootstrap.bash"
end
